module.exports = [
{
	type: "category",
	label: "Blog",
	link: { type: "note", id: "blog" },
	items: [{
		type: "autogenerated",
		id: 'blog'
	}]
},
{
	type: "category",
	label: "Notes",
	link: { type: "note", id: "root" },
	items: [{
		type: "category",
		label: "Electronics",
		link: { type: "note", id: "electronic" },
		items: [{
			type: "autogenerated",
			id: "electronic"
		}]
	},
	{
		type: "category",
		label: "Computer",
		link: {type: "note", id: "computer"},
		items: [{
			type: "autogenerated",
			id: "computer"
				}]
	},
	{
		type: "category",
		label: "Finance",
		link: {type: "note", id: "finance"},
		items: [{
			type: "autogenerated",
			id: "finance"
				}]
	},
	{
		type: "category",
		label: "Mathematics",
		link: {type: "note", id: "math"},
		items: [{
			type: "autogenerated",
			id: "math"
				}]
	},
	{
		type: "category",
		label: "Workflows",
		link: {type: "note", id: "workflows"},
		items: [{
			type: "autogenerated",
			id: "workflows"
				}]
	},
	{
		type: "category",
		label: "Consumer Products",
		link: {type: "note", id: "consumer"},
		items: [{
			type: "autogenerated",
			id: "consumer"
				}]
	}]
}
]
